name: Run content validation

on:
  workflow_run:
    workflows: ["Prepare environment"]
    types:
      - completed

jobs:
  validate_content:
    name: Validate content changes
    runs-on: ubuntu-latest
    env:
      working-directory: ./src
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Download docker artifact
        uses: actions/download-artifact@v2
        with:
          name: hugo_image
          path: /tmp/hugo_image.tar
      - name: Load docker image
        run: docker load --input /tmp/myimage.tar
      - name: Docker images
        run: docker image ls -a
