name: Receive PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate_hugo_content:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src
    name: Hugo content processing
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build Hugo container image
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./src/Dockerfile-build
          # Do not push to remote registry
          push: false
          # Load as a local image
          load: true
          tags: temporary/hugo-ubuntu:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache to keep size low
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Validate Hugo content, internal, and external web links
        run: ./make_hugo.sh -v
        working-directory: ${{env.working-directory}}

      - name: Save PR number
        # Always run to pass the PR# to the next process
        if: success() || failure()
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
